global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    # Prometheus self-monitoring
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    # Auth API
    - job_name: "auth-api"
      static_configs:
          - targets: ["auth-api:8080"]
      metrics_path: "/metrics"
      scrape_interval: 30s

    # Inventory API
    - job_name: "inventory-api"
      static_configs:
          - targets: ["inventory-api:8080"]
      metrics_path: "/metrics"
      scrape_interval: 30s

    # Sales API
    - job_name: "sales-api"
      static_configs:
          - targets: ["sales-api:8080"]
      metrics_path: "/metrics"
      scrape_interval: 30s

    # Gateway API
    - job_name: "gateway"
      static_configs:
          - targets: ["gateway:8080"]
      metrics_path: "/metrics"
      scrape_interval: 30s
