//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Exception.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sales.Exception.ErrorMessages.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao conumir mensagem.
        /// </summary>
        public static string CONSUME_MESSAGE_FAIL {
            get {
                return ResourceManager.GetString("CONSUME_MESSAGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na conexão com o banco de dados.
        /// </summary>
        public static string DB_CONNECTION_FAIL {
            get {
                return ResourceManager.GetString("DB_CONNECTION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao iniciar serviço Message Bus.
        /// </summary>
        public static string MESSAGEBUS_INITIALIZATION {
            get {
                return ResourceManager.GetString("MESSAGEBUS_INITIALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido só pode ser cancelado se estiver Confirmado ou Em Separação.
        /// </summary>
        public static string ORDER_CANNOT_CANCEL {
            get {
                return ResourceManager.GetString("ORDER_CANNOT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível modificar itens de um pedido que não está no status Criado.
        /// </summary>
        public static string ORDER_CANNOT_MODIFY_ITEMS {
            get {
                return ResourceManager.GetString("ORDER_CANNOT_MODIFY_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transição de status inválida para o pedido.
        /// </summary>
        public static string ORDER_INVALID_STATUS_TRANSITION {
            get {
                return ResourceManager.GetString("ORDER_INVALID_STATUS_TRANSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item do pedido não encontrado.
        /// </summary>
        public static string ORDER_ITEM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDER_ITEM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pedido deve conter pelo menos um item.
        /// </summary>
        public static string ORDER_ITEMS_EMPTY {
            get {
                return ResourceManager.GetString("ORDER_ITEMS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço deve ser maior que zero.
        /// </summary>
        public static string PRICE_INVALID {
            get {
                return ResourceManager.GetString("PRICE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID do produto deve ser maior que zero.
        /// </summary>
        public static string PRODUCT_ID_INVALID {
            get {
                return ResourceManager.GetString("PRODUCT_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na mensagem.
        /// </summary>
        public static string PUBLISH_MESSAGE_FAIL {
            get {
                return ResourceManager.GetString("PUBLISH_MESSAGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade deve ser maior que zero.
        /// </summary>
        public static string QUANTITY_INVALID {
            get {
                return ResourceManager.GetString("QUANTITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido.
        /// </summary>
        public static string UNKOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação inválida para o status atual do pedido.
        /// </summary>
        public static string INVALID_ORDER_STATUS_OPERATION {
            get {
                return ResourceManager.GetString("INVALID_ORDER_STATUS_OPERATION", resourceCulture);
            }
        }
    }
}
